spring.application.name=SalesSavvy
server.port=${PORT:10000}

# Database (TiDB Cloud)
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# SendGrid Email
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SENDGRID_API_KEY}   # SendGrid uses API key as password
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Razorpay
razorpay_key_id=${RAZORPAY_KEY_ID}
razorpay_key_secret=${RAZORPAY_KEY_SECRET}

# App Base URL
app.backend.base-url=${APP_BACKEND_BASE_URL:http://localhost:10000}